-- =============================================================================
-- seed.sql — 開発・テスト環境用シードデータ
--
-- WARNING: このファイルは開発・テスト環境専用です。本番環境では実行しないでください。
--
-- 実行方法:
--   supabase db reset  （ローカル環境・マイグレーション適用後に自動実行）
--   psql $DATABASE_URL -f seed.sql  （手動実行）
--
-- ルール:
--   - 冪等に書く（TRUNCATE + INSERT または ON CONFLICT DO NOTHING）
--   - auth.users への直接 INSERT は避ける（Supabase Auth 経由で作成）
-- =============================================================================

-- リソースを追加したらここにシードデータを追記する
-- 例:
-- TRUNCATE TABLE posts CASCADE;
-- INSERT INTO posts (id, title, user_id, created_at, updated_at) VALUES
--   (gen_random_uuid(), 'サンプル投稿', '<auth-user-id>', NOW(), NOW());
